version: "3.3"
services:
  zookeeper:
    image: jplock/zookeeper
    restart: always
    ports:
      - target: 2181
        published: 2181
  rabbitmq:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@queue-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
    volumes:
      - "rabbitmqdisc1_data:/bitnami"
    ports:
      - target: 15678
        published: 15678
  eureka:
    restart: always
    build:
      context: ./external/eureka
      dockerfile: Dockerfile
    ports:
      - target: 8761
        published: 8761
  fanout:
    restart: always
    build:
      context: ./fanout
      dockerfile: Dockerfile
    # deploy:
    #   mode: replicated
    #   replicas: 3
    ports:
      - target: 6001
        published: 6001
    depends_on:
      - zookeeper
      - rabbitmq
      - eureka
  notification:
    restart: always
    build:
      context: ./notif
      dockerfile: Dockerfile
    # deploy:
    #   mode: replicated
    #   replicas: 3
    ports:
      - target: 8000
        published: 8000
    depends_on:
      - fanout
  fls:
    restart: always
    build:
      context: ./notif
      dockerfile: Dockerfile
      #deploy:
      #  mode: replicated
      #  replicas:
    ports:
      - target: 8030
        published: 8030
    depends_on:
      - fanout
  learning:
    restart: always
    build:
      context: ./external/learning
      dockerfile: Dockerfile
    ports:
      - target: 8881
        published: 8881
    depends_on:
      - fls
volumes:
  rabbitmqdisc1_data:
    driver: local
