version: "3.3"
services:
  zookeeper:
    image: jplock/zookeeper
    restart: always
    ports:
      - target: 2181
        published: 2181
  eureka:
    restart: always
    build:
      context: ./external/eureka
      dockerfile: Dockerfile
    ports:
      - target: 8761
        published: 8761
  zuul:
    restart: always
    build:
      context: ./external/zuulgateway
      dockerfile: Dockerfile
    ports:
      - target: 9000
        publiched: 9000
  notification:
    restart: always
    build:
      context: ./notif
      dockerfile: Dockerfile
    # deploy:
    #   mode: replicated
    #   replicas: 3
    ports:
      - target: 8000
        published: 8000
    depends_on:
      - zookeeper
      - eureka
      - zuul
  fls:
    restart: always
    build:
      context: ./notif
      dockerfile: Dockerfile
      #deploy:
      #  mode: replicated
      #  replicas:
    ports:
      - target: 8030
        published: 8030
    depends_on:
      - notification
  learning:
    restart: always
    build:
      context: ./external/learning
      dockerfile: Dockerfile
    ports:
      - target: 8881
        published: 8881
    depends_on:
      - fls
