server:
  port: 9000

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    appname: zuulgateway
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
  serviceURL:
    defaultZone: http://localhost:8761/eureka/apps

zuul:
  routes:
    fls:
      path: /fls/**
      serviceId: fls
    notif:
      path: /notif/**
      serviceId: notif
